MSG_INFO_START = 'Runing Investor Sentiment'
MSG_INFO_LOAD_VIX_DATA_LOCAL = 'Load VIX data from local file.'
MSG_INFO_NO_LOCAL_VIX_DATA = 'No local VIX data exist.Just try to create it.'
MSG_INFO_LOCAL_VIX_DATA_VAILD = 'Local VIX data is valid.!'
MSG_INFO_LOCAL_VIX_DATA_INVAILD = 'Local VIX data may be invalid.Try to download VIX data from yahoo fianance'
MSG_INFO_LOAD_LOCAL_VIX_DATA_SUCCESSED= 'Load load VIX data Successed.length={},timestamp={}'
MSG_INFO_GET_VIX_DATA_YFINANCE_SUCCESSED = 'Download VIX data from Yahoo Finance Successed.time={:.3f}s,length={},timestamp={}'
MSG_INFO_UPDATE_LOCAL_DATA_SUCCESSED = 'Local VIX data update successed.length={}'

MSG_INFO_LOAD_VIX_DATA_LOCAL = 'Load VIX data from local file.'
MSG_INFO_NO_LOCAL_SPX_DATA = 'No local SPX data exist.Just try to create it.'
MSG_INFO_LOCAL_SPX_DATA_VAILD = 'Local SPX data is valid.'
MSG_INFO_LOCAL_SPX_DATA_INVAILD = 'Local SPX data may be invalid.Try to download SPX data from yahoo fianance'
MSG_INFO_LOAD_LOCAL_SPX_DATA_SUCCESSED= 'Load load SPX data Successed.length={},timestamp={}'
MSG_INFO_GET_SPX_DATA_YFINANCE_SUCCESSED = 'Download SPX data from Yahoo Finance Successed.time={:.3f}s,length={},timestamp={}'

MSG_ERROR_ARGS_CONFLICT = 'You cannot update local date in offline mode.Exit!'
MSG_ERROR_GET_VIX_YFINANCE_FAILED = 'Failed to download VIX data from Yahoo Finance.Please check your network connection.Exit!'
MSG_ERROR_GET_SPX_YFINANCE_FAILED = 'Failed to download SPX data from Yahoo Finance.Please check your network connection.Exit!'
MSG_ERROR_UPDATE_LOCAL_DATA_FAILED = 'Failed to update local data.!Please check the disk and permissions.Exit!'
MSG_ERROR_DATA_CONFLICT = 'Internal error. Conflict between VIX data and SPX data. Exit!'
MEG_ERROR_DATA_ERROR = 'Internal error. Data initialization failed. Exit!'